### ISSUE TITLE
Wrong Ruby Version on Semaphore Build

### ISSUE THREAD

**Issue by akosednar** [ugtastic/uglst#2]
Your builds are failing in [semaphore](https://semaphoreci.com/just3ws/uglst/branches/master/builds/68) due to ruby version mismatch.

> Your Ruby version is 2.2.0, but your Gemfile specified 2.2.2

I think the global version you have specified on the settings there overrides the ruby version file in the repo when building.

See: [https://semaphoreci.com/docs/languages/ruby/ruby-support-on-semaphore.html](https://semaphoreci.com/docs/languages/ruby/ruby-support-on-semaphore.html)

**Comment by akosednar** [comment]
You probably know about this but just going through the repo to lend a hand!

**Comment by just3ws** [comment]
Thanks. :)
